### ISSUE TITLE
Desvincular membro não funciona

### ISSUE THREAD

**Issue by AllanNozomu** [cacounicamp/Site-Antigo#14]
A função de desnvicular um membro não está em funcionamento. Pelo que vi não faz nada.

**Comment by rafaelsms** [comment]
De fato :/

É um problema antigo. Para o novo site, vou tentar conversar com os coordenadores para não precisar confirmar, nem remover membros antigos. Tudo pode ser feito com os dados que o IC possui da DAC. Como fiz um site com o coordenador para acompanhamento discente, poderia tentar fazer uma API para verificar se o estudante é/ainda é estudante da computação semestralmente :)

O que acha da ideia?

**Comment by AllanNozomu** [comment]
Partiu férias

**Comment by rafaelsms** [comment]
Foi corrigido no novo site.
